kind: Blueprint
apiVersion: cr.kanister.io/v1alpha1
metadata:
  name: backup-copy-blueprint
  namespace: kasten-io
actions:
  post-export:
    name: ""
    kind: Namespace
    phases:
      - func: KubeTask
        name: backup-copy
        args:
          image: bitnami/kubectl
          command:
            - /bin/sh
            - -c
            - >
              APPLICATION_NAMESPACE="{{ .Namespace.Name }}"

              # Define the secondary location profile depending on your context

              SECONDARY_LOCATION_PROFILE=backup_copy_location

              #Identifying latest local restore point...

              LATEST_RESTORE_POINT=$(kubectl get restorepoints.apps.kio.kasten.io -n $APPLICATION_NAMESPACE \
              --sort-by=.metadata.creationTimestamp -o json | \
                jq -r '.items[] | select(.metadata.labels["k10.kasten.io/exportProfile"] | not) | .metadata.name' | tail -n 1)

              # Create on-demand export action that exports $LATEST_RESTORE_POINT
              # from the $APPLICATION_NAMESPACE using $SECONDARY_LOCATION_PROFILE.
              # Assumes that Veeam Kasten is installed in 'kasten-io' namespace.


              echo | kubectl apply -f - <<EOF

              apiVersion: actions.kio.kasten.io/v1alpha1

              kind: ExportAction

              metadata:
                name: export-$APPLICATION_NAMESPACE-$LATEST_RESTORE_POINT-$SECONDARY_LOCATION_PROFILE
                namespace: kasten-io
                labels:
                  k10.kasten.io/exportType: portableAppData
                  k10.kasten.io/exportProfile: $SECONDARY_LOCATION_PROFILE
                  k10.kasten.io/exportNamespace: $APPLICATION_NAMESPACE
              spec:
                # Expiration timestamp in ``RFC3339`` format. Optional.
                # Garbage collector will automatically retire expired exports if this field is set.
                #expiresAt: "2002-10-02T15:00:00Z"
                expiresAt: $(date -u --date="1 day" "+%Y-%m-%dT%H:%M:%SZ")
                subject:
                  kind: RestorePoint
                  name: $LATEST_RESTORE_POINT
                  namespace: $APPLICATION_NAMESPACE
                profile:
                  name: $SECONDARY_LOCATION_PROFILE
                  namespace: kasten-io
                exportData:
                  enabled: true
              EOF
